version: 2
jobs:
  test:
    docker:
      - image: quay.io/condenastinternational/cnid-node-base:ee12a026576f82cbbce1f414d0ee0eb4f9935aad
    working_directory: ~/conde-nast-international/tftest
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: curl tfjson binary
        command: |
            mkdir -p ~/tmp/bin
            TFJSONBIN=$(curl -XGET https://api.github.com/repos/conde-nast-international/tfjson/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux")) | .browser_download_url')
            curl -L $TFJSONBIN > ~/tmp/bin/tfjson
            chmod +x ~/tmp/bin/tfjson
    - run:
        name: Adds tfjson to PATH
        shell: /bin/bash
        command: |
            echo 'export PATH=~/conde-nast-international/okta-cli/node_modules/.bin:~/tmp/bin:$PATH' >> $BASH_ENV
    - run:
        shell: /bin/bash
        name: Test tftest
        command: npm test
  publish:
    docker:
      - image: quay.io/condenastinternational/cnid-node-base:ee12a026576f82cbbce1f414d0ee0eb4f9935aad
    working_directory: ~/conde-nast-international/tftest
    steps:
    - checkout
    - run:
        name: Add deploy token to npmrc
        command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - deploy:
        name: Push package to npm
        command: npm publish



workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
