version: 2
jobs:
  test:
    docker:
      - image: quay.io/condenastinternational/cnid-node-base:ee12a026576f82cbbce1f414d0ee0eb4f9935aad
    working_directory: ~/conde-nast-international/tftest

    steps:
    - checkout
    - run:
        name: Install dependencies
        shell: /bin/sh -eo pipefail -l
        command: export TERM=dumb && npm install
    - run:
        name: Test tftest
        command: npm test
  publish:
    docker:
      - image: quay.io/condenastinternational/cnid-node-base:ee12a026576f82cbbce1f414d0ee0eb4f9935aad
    working_directory: ~/conde-nast-international/tftest
    steps:
    - checkout
    - run:
        name: Add deploy token to npmrc
        command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - deploy:
        name: Push package to npm
        command: npm publish



workflows:
  version: 2
  deployment_pipeline:
    jobs:
      - test
      - publish_on_hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - publish_on_hold
